width: 32 # In pixels
height: 16 # In pixels
fontPath: ./tom-thumb.pil # Path to your font file
fontHeight: 5 # Vertical size of your font

weather: # Weather module
  darksky_key:  # API key for darksky.net
  latitude:  # Latiude of device
  longitude: # Longitude of device

edinburgh_bus: # Edinburgh Buses (MyBusTracker) module
  stop_id: # MyBusTracker code for the stop you would like to track
  services: [''] # Array of the tracked buses. Strings and maximum 1 per 6px of vertical space.
  api_key: # API key for MyBusTracker

led:
  rows: 32   # Display rows. 16 for 16x32, 32 for 32x32
  chain: 1   # Daisy-chained boards
  parallel: 1 # Parallel chains (for plus-models or RPi2). Range 1 - 3
  pwm_bits: 11   # Bits used for PWM. Range 1 - 11
  brightness: 100   # Sets brightness level. Range 1-100
  gpio_mapping: regular   # GPIO mapping (regular, adafruit-hat, adafruit-hat-pwm)
  scan_mode: 1   # Progressive (0) or interlaced scan (1)
  pwm_lsb_nanoseconds: 130   # Base time-unit for the on-time in the lowest significant bit (in nanosecods)
  show_refresh: True   # Shows the current refresh rate of the LED panel
  slowdown_gpio: 1 # Slow down writing to GPIO. Range 1-100
  no_hardware_pulse: False   # Don't use hardware pin-pulse generation
